Add missing import
erppeek is used in the module:

File "/home/travis/build/camptocamp/predige_openerp/Scenario/OERPScenario/features/steps/dsl.py", line 59, in impl
ctx.found_items = erppeek.RecordList(Model, [])
NameError: global name 'erppeek' is not defined